# generation command: dart run build_runner build -d
targets:
  $default:
    builders:
      drift_dev:
        # disable drift's default builder, using the modular setup instead
        enabled: false
      drift_dev:analyzer:
        enabled: true
        options: &options
          store_date_time_values_as_text: true
          named_parameters: true
          fatal_warnings: true
          generate_manager: false
          data_class_to_companions: false
          sql:
              dialect: sqlite
      drift_dev:modular:
        enabled: true
        options: *options
