name: numly
description: "Minimalist cross-platform mental arithmetic training app."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.6.0

dependencies:
  collection: ^1.19.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  gap: ^3.0.1
  hooks_riverpod: ^2.6.1
  material_symbols_icons: ^4.2815.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
