name: numly
description: "Minimalist cross-platform mental arithmetic training app."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  gap: ^3.0.1
  material_symbols_icons: ^4.2815.0

  collection: ^1.19.0

  go_router: ^15.1.1
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  drift: ^2.26.1
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Command to generate the icons: `dart run flutter_launcher_icons`
  flutter_launcher_icons: ^0.14.3

  # Commands to set the application name:
  # `dart run change_app_package_name:main app.numly.android --android`
  # `dart run change_app_package_name:main app.numly.ios --ios`
  change_app_package_name: ^1.5.0

  flutter_lints: ^5.0.0
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  drift_dev: ^2.26.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: assets/logo/numly.png
  android: true
  web:
    generate: true
